spring.application.name=EDIP

server.port=${PORT:9000}

# ================================
# SQL Server
# ================================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jackson.time-zone=UTC

# ================================
# MongoDB
# ================================
spring.data.mongodb.uri=${MONGO_URI}
spring.data.mongodb.database=EDIP

# ================================
# Mail
# ================================
brevo.api.key=${BREVO_API_KEY}

# ================================
# Frontend
# ================================
app.frontend.url=${FRONTEND_URL:http://localhost:3000}

# ================================
# AI API
# ================================
ai.api.url=${AI_API_URL:https://manarsaber11-document-processor.hf.space/api/v1/process}
rag.base-url=${RAG_BASE_URL:https://manarsaber11-rag.hf.space}
ai.api.key=${AI_API_KEY}
rag.groq-key=${RAG_GROQ_KEY}

# ================================
# JWT
# ================================
jwt.secret=${JWT_SECRET}
jwt.expiration=900000
jwt.refresh-expiration=28800000

# ================================
# File Upload
# ================================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# ================================
# Async Thread Pool
# ================================
spring.task.execution.pool.core-size=5
spring.task.execution.pool.max-size=10
spring.task.execution.pool.queue-capacity=100

# ================================
# AI Retry Scheduler
# ================================
ai.retry.interval-ms=600000
spring.task.scheduling.pool.size=2

# ================================
# Logging
# ================================
logging.level.com.example.EDIP=INFO
logging.level.org.springframework.security=WARN
logging.level.org.hibernate.SQL=WARN

# ================================
# Encryption
# ================================
app.encryption.key=${ENCRYPTION_KEY}

# ================================
# Jackson
# ================================
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.date-format=yyyy-MM-dd HH:mm